---
- hosts: all
  become: yes
  user: vagrant
  tasks:
    - name: apt-get update
      apt: name=* state=latest update_cache=yes
    - name: Install basic packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - nkf
        - vim
        - zsh
