---
- hosts: all
  become: yes
  user: vagrant

  tasks:
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=3600

    - name: install basic packages
      apt: name={{ item }}
      with_items:
        - dstat
        - git
        - nkf
        - vim
        - zsh

